service: guros-challange

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  region: us-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  check:
    handler: dna_check.cerebro
    events:
      - http: 'POST /mutation'
  getstats:
    handler: dynapp.get_stats
    events:
      - http: 'GET /stats'

plugins:
  - serverless-python-requirements

resources:
  Resources:
    DNATable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: dnaId
            AttributeType: S
        KeySchema:
          - AttributeName: dnaId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: dna-table